# This file is auto-generated by GoReleaser during releases.
# Manual edits will be overwritten.
#
# To install: brew install dbmrq/tap/ralph
#
# Note: This formula will be populated when the first release is created.
# Run `goreleaser release` or push a version tag to generate it.

class Ralph < Formula
  desc "AI-powered task automation tool"
  homepage "https://github.com/dbmrq/ralph"
  license "MIT"

  # Placeholder - GoReleaser will update this with actual release URLs
  # version "0.0.0"
  # url "https://github.com/dbmrq/ralph/releases/download/v0.0.0/ralph_0.0.0_Darwin_x86_64.tar.gz"
  # sha256 "placeholder"

  def install
    bin.install "ralph"
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
