# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "AI-powered task automation tool"
  homepage "https://github.com/dbmrq/ralph"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbmrq/ralph/releases/download/v0.1.0/ralph_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "654884832393996a31b35cfd528183b8af7ddbe26cba9bc3d14d6c2b3cb03b20"

      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbmrq/ralph/releases/download/v0.1.0/ralph_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c9fd682ad6adc8a592b02d82e9b7d7388878f05f26615a14eafc65af0485397c"

      def install
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbmrq/ralph/releases/download/v0.1.0/ralph_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7e16324ab55169064ab65cc34e0eb701fde250df99276edb1928bd5fe6d29666"
      def install
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbmrq/ralph/releases/download/v0.1.0/ralph_0.1.0_Linux_arm64.tar.gz"
      sha256 "55f34a1ee9fc33dbb6bee2a43b86033713949886052a981bdde55f2c4e84dcd6"
      def install
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
